<?php

namespace BaseBundle\Repository;

/**
 * ProdFavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdFavRepository extends \Doctrine\ORM\EntityRepository
{
}
