<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPohvgsg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPohvgsg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPohvgsg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPohvgsg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPohvgsg\appDevDebugProjectContainer([
    'container.build_hash' => 'Pohvgsg',
    'container.build_id' => 'efce2f29',
    'container.build_time' => 1555329889,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPohvgsg');
