<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ8y5sqr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ8y5sqr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQ8y5sqr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQ8y5sqr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQ8y5sqr\appDevDebugProjectContainer([
    'container.build_hash' => 'Q8y5sqr',
    'container.build_id' => 'dd5221b7',
    'container.build_time' => 1555354852,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ8y5sqr');
