<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4lkizcr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4lkizcr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4lkizcr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4lkizcr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4lkizcr\appDevDebugProjectContainer([
    'container.build_hash' => '4lkizcr',
    'container.build_id' => '904c369c',
    'container.build_time' => 1553983499,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4lkizcr');
