musee_guide:
    resource: "@MuseeBundle/Resources/config/routing/guide.yml"
    prefix:   /guide

musee_visite:
    resource: "@MuseeBundle/Resources/config/routing/visite.yml"
    prefix:   /visite

musee_homepage:
    path:     /
    defaults: { _controller: MuseeBundle:Default:index }

musee_vit:
    path:     /vv
    defaults: { _controller: MuseeBundle:Visite:new }


guide_recherche:
    path:     /recher
    defaults: { _controller:  MuseeBundle:Guide:recherche }

guide_export:
    path:     /export
    defaults: { _controller: MuseeBundle:Guide:export }

guide_today:
    path :    /today
    defaults: { _controller: MuseeBundle:Guide:today }
visite_all:
    path: /all
    defaults: { _controller: MuseeBundle:Visite:all }
guide_all:
    path: /guidesall
    defaults: {_controller: MuseeBundle:Guide:all}
visite_ajout:
    path: /newvisite
    defaults: {_controller: MuseeBundle:Visite:add}