<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.util.email_canonicalizer' shared service.

include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\FOSUserBundle\\Util\\CanonicalizerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\FOSUserBundle\\Util\\Canonicalizer.php';

return $this->services['fos_user.util.email_canonicalizer'] = new \FOS\UserBundle\Util\Canonicalizer();
