<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSnhcbwv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSnhcbwv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSnhcbwv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSnhcbwv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSnhcbwv\appProdProjectContainer([
    'container.build_hash' => 'Snhcbwv',
    'container.build_id' => '33a428b4',
    'container.build_time' => 1553983368,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSnhcbwv');
