base_ticketstheatre:
    resource: "@BaseBundle/Controller/TicketstheatreController.php"
    type:     annotation

base_ticketsevent:
    resource: "@BaseBundle/Controller/TicketseventController.php"
    type:     annotation

base_ticketsfilm:
    resource: "@BaseBundle/Controller/TicketsfilmController.php"
    type:     annotation

base_salles:
    resource: "@BaseBundle/Controller/SallesController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
base:
    resource: "@BaseBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

